name: app_movil_nuam
description: "Aplicación móvil para Jefe de Equipo - Sistema de Calificaciones Tributarias NUAM"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.2.0
  
  # Persistencia local (sesión)
  shared_preferences: ^2.2.2
  
  # Gráficos
  fl_chart: ^0.68.0
  
  # Formateo de fechas y números
  intl: ^0.19.0
  
  # Iconos
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true